site_name: Python Physics
theme:
  name: material
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: white
      accent: deep orange
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue grey
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - toc:
      toc_depth: 3

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_SVG'

nav:
  - E&amp;M Notebooks: 
    - Plotting Vector Fields: ElecMag/PythonJupyterPlottingVectorFields.md
    - Plotting Vector Fields 2: ElecMag/PythonJupyterPlottingVectorFields2.md
    - "Numerial ODEs: Euler's Method": ElecMag/EulersMethod.md
    - Discretization in 1D: ElecMag/Discretization1D.md
    - Relaxation With Linear Algebra: ElecMag/RelaxationWithLinearAlgebra.md
    - 2D Relaxation: ElecMag/2DRelaxation.md
    - Refining Relaxation: ElecMag/RefiningRelaxation.md
    - Boundary Conditions: ElecMag/BoundaryConditions.md
    
copyright: |
  &copy; 2024 <a href="https://github.com/Hal-Haggard" target="_blank" rel="noopener">Hal Haggard</a>
